### ISSUE TITLE
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by terrycalderbank** [ysh329/darknet2caffe#11]
Hi there,

I just tried to convert my custom YOLOV2 model using the provided script and I received the following:

`nvidia@nvidia-MS-7971:~/Desktop/darknet2caffe$ python darknet2caffe.py yolo-obj.cfg yolo-obj.weights 
Traceback (most recent call last):
  File "darknet2caffe.py", line 660, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 13, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 336, in cfg2prototxt
    if block.has_key['bias_match']:
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
`

**Comment by abx67** [comment]
same error here,

fixed:

change

`if block.has_key['bias_match']:` to `if block.has_key('bias_match'):`
